"""
ESPN Team Mapping Table
Auto-generated from ESPN's team APIs.
Maps lowercase team name variations to (sport, espn_display_name).
"""

# (lowercase_variant) -> (sport_key, official_espn_name)
ESPN_TEAM_MAP = {
    "atl": ("nba", "Atlanta Hawks"),
    "atlanta hawks": ("nba", "Atlanta Hawks"),
    "hawks": ("nba", "Atlanta Hawks"),
    "bos": ("nba", "Boston Celtics"),
    "boston celtics": ("nba", "Boston Celtics"),
    "celtics": ("nba", "Boston Celtics"),
    "bkn": ("nba", "Brooklyn Nets"),
    "brooklyn nets": ("nba", "Brooklyn Nets"),
    "nets": ("nba", "Brooklyn Nets"),
    "cha": ("nba", "Charlotte Hornets"),
    "charlotte hornets": ("nba", "Charlotte Hornets"),
    "hornets": ("nba", "Charlotte Hornets"),
    "bulls": ("nba", "Chicago Bulls"),
    "chi": ("nba", "Chicago Bulls"),
    "chicago bulls": ("nba", "Chicago Bulls"),
    "cavaliers": ("nba", "Cleveland Cavaliers"),
    "cle": ("nba", "Cleveland Cavaliers"),
    "cleveland cavaliers": ("nba", "Cleveland Cavaliers"),
    "dal": ("nba", "Dallas Mavericks"),
    "dallas mavericks": ("nba", "Dallas Mavericks"),
    "mavericks": ("nba", "Dallas Mavericks"),
    "den": ("nba", "Denver Nuggets"),
    "denver nuggets": ("nba", "Denver Nuggets"),
    "nuggets": ("nba", "Denver Nuggets"),
    "det": ("nba", "Detroit Pistons"),
    "detroit pistons": ("nba", "Detroit Pistons"),
    "pistons": ("nba", "Detroit Pistons"),
    "golden state warriors": ("nba", "Golden State Warriors"),
    "gs": ("nba", "Golden State Warriors"),
    "warriors": ("nba", "Golden State Warriors"),
    "hou": ("nba", "Houston Rockets"),
    "houston rockets": ("nba", "Houston Rockets"),
    "rockets": ("nba", "Houston Rockets"),
    "ind": ("nba", "Indiana Pacers"),
    "indiana pacers": ("nba", "Indiana Pacers"),
    "pacers": ("nba", "Indiana Pacers"),
    "clippers": ("nba", "LA Clippers"),
    "la clippers": ("nba", "LA Clippers"),
    "lac": ("nba", "LA Clippers"),
    "lakers": ("nba", "Los Angeles Lakers"),
    "lal": ("nba", "Los Angeles Lakers"),
    "los angeles lakers": ("nba", "Los Angeles Lakers"),
    "grizzlies": ("nba", "Memphis Grizzlies"),
    "mem": ("nba", "Memphis Grizzlies"),
    "memphis grizzlies": ("nba", "Memphis Grizzlies"),
    "heat": ("nba", "Miami Heat"),
    "mia": ("nba", "Miami Heat"),
    "miami heat": ("nba", "Miami Heat"),
    "bucks": ("nba", "Milwaukee Bucks"),
    "mil": ("nba", "Milwaukee Bucks"),
    "milwaukee bucks": ("nba", "Milwaukee Bucks"),
    "min": ("nba", "Minnesota Timberwolves"),
    "minnesota timberwolves": ("nba", "Minnesota Timberwolves"),
    "timberwolves": ("nba", "Minnesota Timberwolves"),
    "new orleans pelicans": ("nba", "New Orleans Pelicans"),
    "no": ("nba", "New Orleans Pelicans"),
    "pelicans": ("nba", "New Orleans Pelicans"),
    "knicks": ("nba", "New York Knicks"),
    "new york knicks": ("nba", "New York Knicks"),
    "ny": ("nba", "New York Knicks"),
    "okc": ("nba", "Oklahoma City Thunder"),
    "oklahoma city thunder": ("nba", "Oklahoma City Thunder"),
    "thunder": ("nba", "Oklahoma City Thunder"),
    "magic": ("nba", "Orlando Magic"),
    "orl": ("nba", "Orlando Magic"),
    "orlando magic": ("nba", "Orlando Magic"),
    "76ers": ("nba", "Philadelphia 76ers"),
    "phi": ("nba", "Philadelphia 76ers"),
    "philadelphia 76ers": ("nba", "Philadelphia 76ers"),
    "phoenix suns": ("nba", "Phoenix Suns"),
    "phx": ("nba", "Phoenix Suns"),
    "suns": ("nba", "Phoenix Suns"),
    "por": ("nba", "Portland Trail Blazers"),
    "portland trail blazers": ("nba", "Portland Trail Blazers"),
    "trail blazers": ("nba", "Portland Trail Blazers"),
    "kings": ("nba", "Sacramento Kings"),
    "sac": ("nba", "Sacramento Kings"),
    "sacramento kings": ("nba", "Sacramento Kings"),
    "sa": ("nba", "San Antonio Spurs"),
    "san antonio spurs": ("nba", "San Antonio Spurs"),
    "spurs": ("nba", "San Antonio Spurs"),
    "raptors": ("nba", "Toronto Raptors"),
    "tor": ("nba", "Toronto Raptors"),
    "toronto raptors": ("nba", "Toronto Raptors"),
    "jazz": ("nba", "Utah Jazz"),
    "utah": ("nba", "Utah Jazz"),
    "utah jazz": ("nba", "Utah Jazz"),
    "washington wizards": ("nba", "Washington Wizards"),
    "wizards": ("nba", "Washington Wizards"),
    "wsh": ("nba", "Washington Wizards"),
    "ari": ("nfl", "Arizona Cardinals"),
    "arizona cardinals": ("nfl", "Arizona Cardinals"),
    "cardinals": ("nfl", "Arizona Cardinals"),
    "atl": ("nfl", "Atlanta Falcons"),
    "atlanta falcons": ("nfl", "Atlanta Falcons"),
    "falcons": ("nfl", "Atlanta Falcons"),
    "bal": ("nfl", "Baltimore Ravens"),
    "baltimore ravens": ("nfl", "Baltimore Ravens"),
    "ravens": ("nfl", "Baltimore Ravens"),
    "bills": ("nfl", "Buffalo Bills"),
    "buf": ("nfl", "Buffalo Bills"),
    "buffalo bills": ("nfl", "Buffalo Bills"),
    "car": ("nfl", "Carolina Panthers"),
    "carolina panthers": ("nfl", "Carolina Panthers"),
    "panthers": ("nfl", "Carolina Panthers"),
    "bears": ("nfl", "Chicago Bears"),
    "chi": ("nfl", "Chicago Bears"),
    "chicago bears": ("nfl", "Chicago Bears"),
    "bengals": ("nfl", "Cincinnati Bengals"),
    "cin": ("nfl", "Cincinnati Bengals"),
    "cincinnati bengals": ("nfl", "Cincinnati Bengals"),
    "browns": ("nfl", "Cleveland Browns"),
    "cle": ("nfl", "Cleveland Browns"),
    "cleveland browns": ("nfl", "Cleveland Browns"),
    "cowboys": ("nfl", "Dallas Cowboys"),
    "dal": ("nfl", "Dallas Cowboys"),
    "dallas cowboys": ("nfl", "Dallas Cowboys"),
    "broncos": ("nfl", "Denver Broncos"),
    "den": ("nfl", "Denver Broncos"),
    "denver broncos": ("nfl", "Denver Broncos"),
    "det": ("nfl", "Detroit Lions"),
    "detroit lions": ("nfl", "Detroit Lions"),
    "lions": ("nfl", "Detroit Lions"),
    "gb": ("nfl", "Green Bay Packers"),
    "green bay packers": ("nfl", "Green Bay Packers"),
    "packers": ("nfl", "Green Bay Packers"),
    "hou": ("nfl", "Houston Texans"),
    "houston texans": ("nfl", "Houston Texans"),
    "texans": ("nfl", "Houston Texans"),
    "colts": ("nfl", "Indianapolis Colts"),
    "ind": ("nfl", "Indianapolis Colts"),
    "indianapolis colts": ("nfl", "Indianapolis Colts"),
    "jacksonville jaguars": ("nfl", "Jacksonville Jaguars"),
    "jaguars": ("nfl", "Jacksonville Jaguars"),
    "jax": ("nfl", "Jacksonville Jaguars"),
    "chiefs": ("nfl", "Kansas City Chiefs"),
    "kansas city chiefs": ("nfl", "Kansas City Chiefs"),
    "kc": ("nfl", "Kansas City Chiefs"),
    "las vegas raiders": ("nfl", "Las Vegas Raiders"),
    "lv": ("nfl", "Las Vegas Raiders"),
    "raiders": ("nfl", "Las Vegas Raiders"),
    "chargers": ("nfl", "Los Angeles Chargers"),
    "lac": ("nfl", "Los Angeles Chargers"),
    "los angeles chargers": ("nfl", "Los Angeles Chargers"),
    "lar": ("nfl", "Los Angeles Rams"),
    "los angeles rams": ("nfl", "Los Angeles Rams"),
    "rams": ("nfl", "Los Angeles Rams"),
    "dolphins": ("nfl", "Miami Dolphins"),
    "mia": ("nfl", "Miami Dolphins"),
    "miami dolphins": ("nfl", "Miami Dolphins"),
    "min": ("nfl", "Minnesota Vikings"),
    "minnesota vikings": ("nfl", "Minnesota Vikings"),
    "vikings": ("nfl", "Minnesota Vikings"),
    "ne": ("nfl", "New England Patriots"),
    "new england patriots": ("nfl", "New England Patriots"),
    "patriots": ("nfl", "New England Patriots"),
    "new orleans saints": ("nfl", "New Orleans Saints"),
    "no": ("nfl", "New Orleans Saints"),
    "saints": ("nfl", "New Orleans Saints"),
    "giants": ("nfl", "New York Giants"),
    "new york giants": ("nfl", "New York Giants"),
    "nyg": ("nfl", "New York Giants"),
    "jets": ("nfl", "New York Jets"),
    "new york jets": ("nfl", "New York Jets"),
    "nyj": ("nfl", "New York Jets"),
    "eagles": ("nfl", "Philadelphia Eagles"),
    "phi": ("nfl", "Philadelphia Eagles"),
    "philadelphia eagles": ("nfl", "Philadelphia Eagles"),
    "pit": ("nfl", "Pittsburgh Steelers"),
    "pittsburgh steelers": ("nfl", "Pittsburgh Steelers"),
    "steelers": ("nfl", "Pittsburgh Steelers"),
    "49ers": ("nfl", "San Francisco 49ers"),
    "san francisco 49ers": ("nfl", "San Francisco 49ers"),
    "sf": ("nfl", "San Francisco 49ers"),
    "sea": ("nfl", "Seattle Seahawks"),
    "seahawks": ("nfl", "Seattle Seahawks"),
    "seattle seahawks": ("nfl", "Seattle Seahawks"),
    "buccaneers": ("nfl", "Tampa Bay Buccaneers"),
    "tampa bay buccaneers": ("nfl", "Tampa Bay Buccaneers"),
    "tb": ("nfl", "Tampa Bay Buccaneers"),
    "ten": ("nfl", "Tennessee Titans"),
    "tennessee titans": ("nfl", "Tennessee Titans"),
    "titans": ("nfl", "Tennessee Titans"),
    "commanders": ("nfl", "Washington Commanders"),
    "washington commanders": ("nfl", "Washington Commanders"),
    "wsh": ("nfl", "Washington Commanders"),
    "ari": ("mlb", "Arizona Diamondbacks"),
    "arizona diamondbacks": ("mlb", "Arizona Diamondbacks"),
    "diamondbacks": ("mlb", "Arizona Diamondbacks"),
    "ath": ("mlb", "Athletics"),
    "athletics": ("mlb", "Athletics"),
    "athletics athletics": ("mlb", "Athletics"),
    "atl": ("mlb", "Atlanta Braves"),
    "atlanta braves": ("mlb", "Atlanta Braves"),
    "braves": ("mlb", "Atlanta Braves"),
    "bal": ("mlb", "Baltimore Orioles"),
    "baltimore orioles": ("mlb", "Baltimore Orioles"),
    "orioles": ("mlb", "Baltimore Orioles"),
    "bos": ("mlb", "Boston Red Sox"),
    "boston red sox": ("mlb", "Boston Red Sox"),
    "red sox": ("mlb", "Boston Red Sox"),
    "chc": ("mlb", "Chicago Cubs"),
    "chicago cubs": ("mlb", "Chicago Cubs"),
    "cubs": ("mlb", "Chicago Cubs"),
    "chicago white sox": ("mlb", "Chicago White Sox"),
    "chw": ("mlb", "Chicago White Sox"),
    "white sox": ("mlb", "Chicago White Sox"),
    "cin": ("mlb", "Cincinnati Reds"),
    "cincinnati reds": ("mlb", "Cincinnati Reds"),
    "reds": ("mlb", "Cincinnati Reds"),
    "cle": ("mlb", "Cleveland Guardians"),
    "cleveland guardians": ("mlb", "Cleveland Guardians"),
    "guardians": ("mlb", "Cleveland Guardians"),
    "col": ("mlb", "Colorado Rockies"),
    "colorado rockies": ("mlb", "Colorado Rockies"),
    "rockies": ("mlb", "Colorado Rockies"),
    "det": ("mlb", "Detroit Tigers"),
    "detroit tigers": ("mlb", "Detroit Tigers"),
    "tigers": ("mlb", "Detroit Tigers"),
    "astros": ("mlb", "Houston Astros"),
    "hou": ("mlb", "Houston Astros"),
    "houston astros": ("mlb", "Houston Astros"),
    "kansas city royals": ("mlb", "Kansas City Royals"),
    "kc": ("mlb", "Kansas City Royals"),
    "royals": ("mlb", "Kansas City Royals"),
    "angels": ("mlb", "Los Angeles Angels"),
    "laa": ("mlb", "Los Angeles Angels"),
    "los angeles angels": ("mlb", "Los Angeles Angels"),
    "dodgers": ("mlb", "Los Angeles Dodgers"),
    "lad": ("mlb", "Los Angeles Dodgers"),
    "los angeles dodgers": ("mlb", "Los Angeles Dodgers"),
    "marlins": ("mlb", "Miami Marlins"),
    "mia": ("mlb", "Miami Marlins"),
    "miami marlins": ("mlb", "Miami Marlins"),
    "brewers": ("mlb", "Milwaukee Brewers"),
    "mil": ("mlb", "Milwaukee Brewers"),
    "milwaukee brewers": ("mlb", "Milwaukee Brewers"),
    "min": ("mlb", "Minnesota Twins"),
    "minnesota twins": ("mlb", "Minnesota Twins"),
    "twins": ("mlb", "Minnesota Twins"),
    "mets": ("mlb", "New York Mets"),
    "new york mets": ("mlb", "New York Mets"),
    "nym": ("mlb", "New York Mets"),
    "new york yankees": ("mlb", "New York Yankees"),
    "nyy": ("mlb", "New York Yankees"),
    "yankees": ("mlb", "New York Yankees"),
    "phi": ("mlb", "Philadelphia Phillies"),
    "philadelphia phillies": ("mlb", "Philadelphia Phillies"),
    "phillies": ("mlb", "Philadelphia Phillies"),
    "pirates": ("mlb", "Pittsburgh Pirates"),
    "pit": ("mlb", "Pittsburgh Pirates"),
    "pittsburgh pirates": ("mlb", "Pittsburgh Pirates"),
    "padres": ("mlb", "San Diego Padres"),
    "san diego padres": ("mlb", "San Diego Padres"),
    "sd": ("mlb", "San Diego Padres"),
    "giants": ("mlb", "San Francisco Giants"),
    "san francisco giants": ("mlb", "San Francisco Giants"),
    "sf": ("mlb", "San Francisco Giants"),
    "mariners": ("mlb", "Seattle Mariners"),
    "sea": ("mlb", "Seattle Mariners"),
    "seattle mariners": ("mlb", "Seattle Mariners"),
    "cardinals": ("mlb", "St. Louis Cardinals"),
    "st. louis cardinals": ("mlb", "St. Louis Cardinals"),
    "stl": ("mlb", "St. Louis Cardinals"),
    "rays": ("mlb", "Tampa Bay Rays"),
    "tampa bay rays": ("mlb", "Tampa Bay Rays"),
    "tb": ("mlb", "Tampa Bay Rays"),
    "rangers": ("mlb", "Texas Rangers"),
    "tex": ("mlb", "Texas Rangers"),
    "texas rangers": ("mlb", "Texas Rangers"),
    "blue jays": ("mlb", "Toronto Blue Jays"),
    "tor": ("mlb", "Toronto Blue Jays"),
    "toronto blue jays": ("mlb", "Toronto Blue Jays"),
    "nationals": ("mlb", "Washington Nationals"),
    "washington nationals": ("mlb", "Washington Nationals"),
    "wsh": ("mlb", "Washington Nationals"),
    "ana": ("nhl", "Anaheim Ducks"),
    "anaheim ducks": ("nhl", "Anaheim Ducks"),
    "ducks": ("nhl", "Anaheim Ducks"),
    "bos": ("nhl", "Boston Bruins"),
    "boston bruins": ("nhl", "Boston Bruins"),
    "bruins": ("nhl", "Boston Bruins"),
    "buf": ("nhl", "Buffalo Sabres"),
    "buffalo sabres": ("nhl", "Buffalo Sabres"),
    "sabres": ("nhl", "Buffalo Sabres"),
    "calgary flames": ("nhl", "Calgary Flames"),
    "cgy": ("nhl", "Calgary Flames"),
    "flames": ("nhl", "Calgary Flames"),
    "car": ("nhl", "Carolina Hurricanes"),
    "carolina hurricanes": ("nhl", "Carolina Hurricanes"),
    "hurricanes": ("nhl", "Carolina Hurricanes"),
    "blackhawks": ("nhl", "Chicago Blackhawks"),
    "chi": ("nhl", "Chicago Blackhawks"),
    "chicago blackhawks": ("nhl", "Chicago Blackhawks"),
    "avalanche": ("nhl", "Colorado Avalanche"),
    "col": ("nhl", "Colorado Avalanche"),
    "colorado avalanche": ("nhl", "Colorado Avalanche"),
    "blue jackets": ("nhl", "Columbus Blue Jackets"),
    "cbj": ("nhl", "Columbus Blue Jackets"),
    "columbus blue jackets": ("nhl", "Columbus Blue Jackets"),
    "dal": ("nhl", "Dallas Stars"),
    "dallas stars": ("nhl", "Dallas Stars"),
    "stars": ("nhl", "Dallas Stars"),
    "det": ("nhl", "Detroit Red Wings"),
    "detroit red wings": ("nhl", "Detroit Red Wings"),
    "red wings": ("nhl", "Detroit Red Wings"),
    "edm": ("nhl", "Edmonton Oilers"),
    "edmonton oilers": ("nhl", "Edmonton Oilers"),
    "oilers": ("nhl", "Edmonton Oilers"),
    "fla": ("nhl", "Florida Panthers"),
    "florida panthers": ("nhl", "Florida Panthers"),
    "panthers": ("nhl", "Florida Panthers"),
    "kings": ("nhl", "Los Angeles Kings"),
    "la": ("nhl", "Los Angeles Kings"),
    "los angeles kings": ("nhl", "Los Angeles Kings"),
    "min": ("nhl", "Minnesota Wild"),
    "minnesota wild": ("nhl", "Minnesota Wild"),
    "wild": ("nhl", "Minnesota Wild"),
    "canadiens": ("nhl", "Montreal Canadiens"),
    "montreal canadiens": ("nhl", "Montreal Canadiens"),
    "mtl": ("nhl", "Montreal Canadiens"),
    "nashville predators": ("nhl", "Nashville Predators"),
    "nsh": ("nhl", "Nashville Predators"),
    "predators": ("nhl", "Nashville Predators"),
    "devils": ("nhl", "New Jersey Devils"),
    "new jersey devils": ("nhl", "New Jersey Devils"),
    "nj": ("nhl", "New Jersey Devils"),
    "islanders": ("nhl", "New York Islanders"),
    "new york islanders": ("nhl", "New York Islanders"),
    "nyi": ("nhl", "New York Islanders"),
    "new york rangers": ("nhl", "New York Rangers"),
    "nyr": ("nhl", "New York Rangers"),
    "rangers": ("nhl", "New York Rangers"),
    "ott": ("nhl", "Ottawa Senators"),
    "ottawa senators": ("nhl", "Ottawa Senators"),
    "senators": ("nhl", "Ottawa Senators"),
    "flyers": ("nhl", "Philadelphia Flyers"),
    "phi": ("nhl", "Philadelphia Flyers"),
    "philadelphia flyers": ("nhl", "Philadelphia Flyers"),
    "penguins": ("nhl", "Pittsburgh Penguins"),
    "pit": ("nhl", "Pittsburgh Penguins"),
    "pittsburgh penguins": ("nhl", "Pittsburgh Penguins"),
    "san jose sharks": ("nhl", "San Jose Sharks"),
    "sharks": ("nhl", "San Jose Sharks"),
    "sj": ("nhl", "San Jose Sharks"),
    "kraken": ("nhl", "Seattle Kraken"),
    "sea": ("nhl", "Seattle Kraken"),
    "seattle kraken": ("nhl", "Seattle Kraken"),
    "blues": ("nhl", "St. Louis Blues"),
    "st. louis blues": ("nhl", "St. Louis Blues"),
    "stl": ("nhl", "St. Louis Blues"),
    "lightning": ("nhl", "Tampa Bay Lightning"),
    "tampa bay lightning": ("nhl", "Tampa Bay Lightning"),
    "tb": ("nhl", "Tampa Bay Lightning"),
    "maple leafs": ("nhl", "Toronto Maple Leafs"),
    "tor": ("nhl", "Toronto Maple Leafs"),
    "toronto maple leafs": ("nhl", "Toronto Maple Leafs"),
    "mammoth": ("nhl", "Utah Mammoth"),
    "utah": ("nhl", "Utah Mammoth"),
    "utah mammoth": ("nhl", "Utah Mammoth"),
    "canucks": ("nhl", "Vancouver Canucks"),
    "van": ("nhl", "Vancouver Canucks"),
    "vancouver canucks": ("nhl", "Vancouver Canucks"),
    "golden knights": ("nhl", "Vegas Golden Knights"),
    "vegas golden knights": ("nhl", "Vegas Golden Knights"),
    "vgk": ("nhl", "Vegas Golden Knights"),
    "capitals": ("nhl", "Washington Capitals"),
    "washington capitals": ("nhl", "Washington Capitals"),
    "wsh": ("nhl", "Washington Capitals"),
    "jets": ("nhl", "Winnipeg Jets"),
    "winnipeg jets": ("nhl", "Winnipeg Jets"),
    "wpg": ("nhl", "Winnipeg Jets"),
    "afc bournemouth": ("epl", "AFC Bournemouth"),
    "afc bournemouth afc bournemouth": ("epl", "AFC Bournemouth"),
    "bou": ("epl", "AFC Bournemouth"),
    "bournemouth": ("epl", "AFC Bournemouth"),
    "ars": ("epl", "Arsenal"),
    "arsenal": ("epl", "Arsenal"),
    "arsenal arsenal": ("epl", "Arsenal"),
    "aston villa": ("epl", "Aston Villa"),
    "aston villa aston villa": ("epl", "Aston Villa"),
    "avl": ("epl", "Aston Villa"),
    "bre": ("epl", "Brentford"),
    "brentford": ("epl", "Brentford"),
    "brentford brentford": ("epl", "Brentford"),
    "bha": ("epl", "Brighton & Hove Albion"),
    "brighton": ("epl", "Brighton & Hove Albion"),
    "brighton & hove albion": ("epl", "Brighton & Hove Albion"),
    "brighton & hove albion brighton & hove albion": ("epl", "Brighton & Hove Albion"),
    "bur": ("epl", "Burnley"),
    "burnley": ("epl", "Burnley"),
    "burnley burnley": ("epl", "Burnley"),
    "che": ("epl", "Chelsea"),
    "chelsea": ("epl", "Chelsea"),
    "chelsea chelsea": ("epl", "Chelsea"),
    "c palace": ("epl", "Crystal Palace"),
    "cry": ("epl", "Crystal Palace"),
    "crystal palace": ("epl", "Crystal Palace"),
    "crystal palace crystal palace": ("epl", "Crystal Palace"),
    "eve": ("epl", "Everton"),
    "everton": ("epl", "Everton"),
    "everton everton": ("epl", "Everton"),
    "ful": ("epl", "Fulham"),
    "fulham": ("epl", "Fulham"),
    "fulham fulham": ("epl", "Fulham"),
    "lee": ("epl", "Leeds United"),
    "leeds": ("epl", "Leeds United"),
    "leeds united": ("epl", "Leeds United"),
    "leeds united leeds united": ("epl", "Leeds United"),
    "liv": ("epl", "Liverpool"),
    "liverpool": ("epl", "Liverpool"),
    "liverpool liverpool": ("epl", "Liverpool"),
    "man city": ("epl", "Manchester City"),
    "manchester city": ("epl", "Manchester City"),
    "manchester city manchester city": ("epl", "Manchester City"),
    "mnc": ("epl", "Manchester City"),
    "man": ("epl", "Manchester United"),
    "man united": ("epl", "Manchester United"),
    "manchester united": ("epl", "Manchester United"),
    "manchester united manchester united": ("epl", "Manchester United"),
    "new": ("epl", "Newcastle United"),
    "newcastle": ("epl", "Newcastle United"),
    "newcastle united": ("epl", "Newcastle United"),
    "newcastle united newcastle united": ("epl", "Newcastle United"),
    "nfo": ("epl", "Nottingham Forest"),
    "nottingham forest": ("epl", "Nottingham Forest"),
    "nottingham forest nottingham forest": ("epl", "Nottingham Forest"),
    "nottm forest": ("epl", "Nottingham Forest"),
    "sun": ("epl", "Sunderland"),
    "sunderland": ("epl", "Sunderland"),
    "sunderland sunderland": ("epl", "Sunderland"),
    "spurs": ("epl", "Tottenham Hotspur"),
    "tot": ("epl", "Tottenham Hotspur"),
    "tottenham hotspur": ("epl", "Tottenham Hotspur"),
    "tottenham hotspur tottenham hotspur": ("epl", "Tottenham Hotspur"),
    "west ham": ("epl", "West Ham United"),
    "west ham united": ("epl", "West Ham United"),
    "west ham united west ham united": ("epl", "West Ham United"),
    "whu": ("epl", "West Ham United"),
    "wol": ("epl", "Wolverhampton Wanderers"),
    "wolverhampton wanderers": ("epl", "Wolverhampton Wanderers"),
    "wolverhampton wanderers wolverhampton wanderers": ("epl", "Wolverhampton Wanderers"),
    "wolves": ("epl", "Wolverhampton Wanderers"),
}

# Minimum alias length for matching (skip abbreviations and short words)
_MIN_ALIAS_LEN = 6

# Build a safe lookup list: only aliases that are long enough and specific enough
_SAFE_ALIASES = sorted(
    [(alias, sport_team) for alias, sport_team in ESPN_TEAM_MAP.items()
     if len(alias) >= _MIN_ALIAS_LEN],
    key=lambda x: len(x[0]),
    reverse=True  # Longest first
)

def lookup_team(text: str):
    """Find an ESPN team in the given text. Returns (sport, espn_name) or None.
    
    Uses word-boundary matching with minimum alias length to avoid
    false positives like 'la' matching 'La Liga'.
    """
    import re
    text_lower = text.lower()
    
    for alias, sport_team in _SAFE_ALIASES:
        pattern = r'\b' + re.escape(alias) + r'\b'
        if re.search(pattern, text_lower):
            return sport_team
    
    return None
